travis:
  secure:
    BINSTAR_TOKEN: hVDdvKafC36t8ws+3v0ZbWsAwj9FgcoLYNYQqOfsZvllw+oanNjfk6JNXoHt0tTx0f2KavyI2E38Rq5X90HbnUEzMeZqeWR1kivKHrRIX3GOEKkoVYaJVoaWLSr2RsmB7BuKDY/G/6HinnKgzbk104T6IYj3BvOR7CJTfkIxgUnB8ZNdQuEkM7ghEQpang4JBuUTUDUB/vUC/70sfozIrD/z9CmZ44pyRwksIAQ5jVTpfvwR4uesPdlWnnyMXUTn4ZbpI27w20Pgitf9dv5d7Uk12int6T3FLGqcwkvhAaag0379A6g7EJkP++Qq9+MFe0WoeHoop8EsQo34OHCHPoNQa+x+ykRtwKIB8gRaNDVXZEr0qivtuFwZcftccVvMeYrXMyw7a6CNcj6Pso14skvKuYymynZltMFkWJ9e4FKe8ICZkdY4a1Rn9Jd+bq6nBHeO2eLlC+WmamoGT1wt2zfM+EVoND36wUH/mgH8+Mm6INMS/k4mCS5k390wyaHgnyXGdQ6/qI7TXlpfiffyaCICp3z2gpHd6GXcddJM1VKEYj1pCMJC7Zx8KkjcOm2wGEgzty/t/ydTaJ366wxJ/mUGS+A9HZjwkSN7HY9Lj95X5H+gWRkhHnviAU6QVjvMcaFU2F3iU00Pcs2DpOmXI+bfRhfvLyVnqv1pSWP6gkQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
